<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>qiling_kinematics_real</name>
  <version>0.1.0</version>
  <description>真机专用 C++ Pinocchio + ProxSuite 双臂差分 IK。</description>
  <maintainer email="user@example.com">qiling</maintainer>
  <license>TODO</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>ament_index_cpp</depend>
  <depend>geometry_msgs</depend>
  <depend>mit_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>std_srvs</depend>
  <depend>qi_robot_description</depend>
  <depend>eigen</depend>
  <depend>pinocchio</depend>
  <depend>proxsuite</depend>
  <depend>qi</depend>
  <exec_depend>ament_index_python</exec_depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
